version: "3"

services:
#   nginx_of_security_app:
#     image: nginx:alpine
#     container_name: nginx_of_security_app
#     restart: unless-stopped


#     volumes:
#       - "./static:/src/static:ro"
#       - "./media:/src/media:rw"
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

#     links:
#       - security_app

# #    expose:
# #      - "98"

#     logging:
#       driver: "json-file"
#       options:
#         max-size: "50m"

#     networks:
#       security_app_net:
#         ipv4_address: 172.45.1.70

  postgres_of_security_app:
    image: postgres:13.1
    restart: always

    environment:
      POSTGRES_PASSWORD: BasiRanjBordamDarin35Sal
      POSTGRES_USER: security_app_usr
      POSTGRES_DB: security_app_db

    logging:
      driver: "json-file"
      options:
        max-size: "50m"

    networks:
      security_app_net:
        ipv4_address: 172.42.1.71

  security_app:
    build: .
    image: security_app_1.0.0
    container_name: security_app
    command: bash bashes/createDB.sh
    restart: unless-stopped
    volumes:
      - "./src:/src"
      - "./media:/code/media:rw"
      - "./static:/code/static:rw"
      - "./security_service/migrations:/src/security_service/migrations:rw"


    ports:
      - 8000:8000

    links:
      - postgres_of_security_app

    logging:
      driver: "json-file"
      options:
        max-size: "50m"

    networks:
      security_app_net:
        ipv4_address: 172.45.1.72




networks:
    security_app_net:
        ipam:
            driver: default
            config:
                - subnet: 172.45.1.0/16
